substitutions:
  system_name: weather_station_air
  friendly_name: Esph Weath Station Air

esphome:
  name: "esph_${system_name}"
  platform: ESP32
  board: pico32

wifi:
  ssid: !secret wifi_vlan1_ssid
  password: !secret wifi_vlan1_password
  fast_connect: true
  ap:
    ssid: "${friendly_name} AP"
    password: !secret fallback_ssid_password

captive_portal:

logger:
  level: VERY_VERBOSE

api:
  password: !secret api_password

ota:
  password: !secret ota_password

web_server:
  port: 80
  
text_sensor:

  - platform: version
    name: "esph_${system_name}_version"
    
i2c:

  - id: i2c_1
    sda: 21
    scl: 22
    scan: True
    
  - id: i2c_2
    sda: 33
    scl: 32
    scan: True
    
sensor:

  - platform: wifi_signal
    name: "esph_${system_name}_wifi_signal"
    update_interval: 30s

  - platform: uptime
    name: "esph_${system_name}_uptime"
    update_interval: 60s

  - platform: sgp30
    i2c_id: i2c_2
    address: 0x58
    eco2:
      name: "esph_${system_name}_eCO2"
      accuracy_decimals: 1
    tvoc:
      name: "esph_${system_name}_TVOC"
      accuracy_decimals: 1
    compensation:
      temperature_source: temperature
      humidity_source: humidity
    update_interval: 30s
    baseline: 0xF8F8
      
  - platform: bme680
    i2c_id: i2c_2  
    address: 0x77
    temperature:
      name: "esph_${system_name}_temperature"
      id: temperature
      oversampling: 16x
    pressure:
      name: "esph_${system_name}_pressure"
    humidity:
      name: "esph_${system_name}_humidity"
      id: humidity
    gas_resistance:
      name: "esph_${system_name}_gas_resistance"
    update_interval: 30s
